export enum CommonStatus {
  ACTIVE = "ACT",
  INACTIVE = "IACT",
  PACTIVE = "PACT",
  PENDING = "PENDING",
  SUCCESS = 'SUCCESS',
  FAIL = 'FAIL',
  REQUIRED = 'REQUIRED',
  OPTIONAL = 'OPTIONAL',
  RESIGN = 'RESIGN',
  REJECT = 'REJ',
  RETURN = 'RETURN'
}
