export enum ExtractRequestWorkflowStages {
  EXTRACT_REQ_INITIALIZED = "EXT_REQ_INT",
  EXTRACT_REQ_INITIALIZED_FOR_ARL = "EXT_REQ_INT_FOR_ARL",
  EXTRACT_REQ_INITIALIZED_FOR_CLARK  = "EXT_REQ_INT_FOR_CLARK",
  EXTRACT_REQ_REJECTED_BY_ARL = "EXT_REQ_ARL_REJ",
  EXTRACT_REQ_RETURN_BY_ARL = "EXT_REQ_ARL_RTN",
  EXTRACT_REQ_ASSIGN_BY_ARL = "EXT_REQ_ARL_ASN",
  EXTRACT_REQ_PRINTED_BY_CLERK = "EXT_REQ_CLK_PRNT",
  EXTRACT_REQ_MODIFIED = "EXT_REQ_MOD",
}
