export enum FolioCorrectionWorkflowStages {
    APPLICANT_INITIATE = 'FOLC_USR_INI',
    APPLICANT_MODIFIED = 'FOLC_USR_MDF',
    RL_RETURN = 'FOLC_RET_APP_RL',
    REQ_REJECTED_TO_APPLICANT_BY_RL = 'FOLC_REJ_APP_RL'
}
