export enum JudicialChangeWorkflowStagesEnum {
  JUDICIAL_CHANGE_REQUEST_INITIALIZED = 'NTR_JZC_CNG_USR_INT',
  JUDICIAL_CHANGE_REQUEST_INITIATED = 'NTR_JZC_CNG_USR_INT',
  DATA_VERIFICATION_CLERK_VERIFIED = 'NTR_JZC_CNG_DVC_VER',
  DATA_VERIFICATION_CLERK_REJECTED= 'NTR_JZC_CNG_DVC_REJ',
  JUDICIAL_CHANGE_REQUEST_MODIFIED= 'NTR_JZC_CNG_USR_MOD',
  JUDICIAL_CHANGE_REQUEST_APPROVED_ARL= 'NTR_JZC_CNG_ARL_APR',
  JUDICIAL_CHANGE_REQUEST_REJECTED_ARL= 'NTR_JZC_CNG_ARL_REJ',
  JUDICIAL_CHANGE_REQUEST_MODIFIED_DVC= 'NTR_JZC_CNG_DVC_MOD',
  JUDICIAL_CHANGE_REQUEST_MODIFIED_ARL= 'NTR_JZC_CNG_ARL_MOD',
  JUDICIAL_CHANGE_REQUEST_PRINTED_MA= 'NTR_JZC_CNG_MA_PRNT',
  JUDICIAL_CHANGE_REQUEST_COMPLETED_MA= 'NTR_JZC_CNG_MA_COM',
  JUDICIAL_CHANGE_REQUEST_ISSUED_SC= 'NTR_JZC_CNG_SC_ISD',
  JUDICIAL_CHANGE_REQUEST_APPROVED_ARG= 'NTR_JZC_CNG_ARG_APR',
  JUDICIAL_CHANGE_REQUEST_REJECTED_ARG= 'NTR_JZC_CNG_ARG_REJ',

}
