export enum LandRegistryChangeWorkflowStagesEnum {
  LANDREGISTRY_CHANGE_REQUEST_INITIATED = 'LNDREG_CHG_REQ_INT',
  LANDREGISTRY_CHANGE_REQUEST_APPROVED_BY_ARG = 'LNDREG_CHG_REQ_AP_ARG',
  LANDREGISTRY_CHANGE_REQUEST_REJECTED_BY_ARG = 'LNDREG_CHG_REQ_RJ_ARG',
  LANDREGISTRY_CHANGE_REQUEST_REJECTED_BY_RL = 'LNDREG_CHG_REQ_RJ_RL',



}
