export enum LanguageChangeWorkflowStages {
    LANGUAGE_CHANGE_REQUEST_INIT = 'LAN_REQ_INI',
    LANGUAGE_CHANGE_REQUEST_APPROVE_DVC = 'LAN_REQ_FRW_SC',
    LANGUAGE_CHANGE_REQUEST_RETURN_DVC = 'LAN_REQ_RET_SC',
}
