export enum NameChangeWorkflowStagesEnum {
  NAME_CHANGE_REQUEST_INITIALIZED = 'NTR_NME_CNG_REQ_INT',
  NOTARY_NAME_CHANGE_REQUEST_MODIFIED ='NTR_NME_CNG_USR_MOD',
  NOTARY_NAME_CHANGE_DATA_VERIFICATION_CLERK_REJECTED = 'NTR_NME_CNG_DVC_REJ',
  NOTARY_NAME_CHANGE_DATA_VERIFICATION_CLERK_VERIFIED = 'NTR_NME_CNG_DVC_VER',
  NOTARY_NAME_CHANGE_REQUEST_APPROVED_ARL = 'NTR_NME_CNG_ARL_APR',
  NOTARY_NAME_CHANGE_REQUEST_REJECTED_ARL = 'NTR_NME_CNG_ARL_REJ',
  NOTARY_NAME_CHANGE_REQUEST_MODIFIED_DVC = 'NTR_NME_CNG_DVC_MOD',
  NOTARY_NAME_CHANGE_REQUEST_MODIFIED_ARL = 'NTR_NME_CNG_ARL_MOD',
  NOTARY_NAME_CHANGE_REQUEST_PRINTED_MA = 'NTR_NME_CNG_MA_PRNT',
  NOTARY_NAME_CHANGE_REQUEST_COMPLETED_MA = 'NTR_NME_CNG_MA_COM',
  NOTARY_NAME_CHANGE_REQUEST_ISSUED_SC = 'NTR_NME_CNG_SC_ISD',
  NOTARY_NAME_CHANGE_REQUEST_ISSUED = 'NTR_NME_CNG_ISSUED',
  NOTARY_NAME_CHANGE_REQUEST_APPROVED_ARG = 'NTR_NME_CNG_ARG_APR',
  NOTARY_NAME_CHANGE_REQUEST_REJECTED_ARG = 'NTR_NME_CNG_ARG_REJ'
}
