export enum NameChangeWorkflowStagesEnum {
  NAME_CHANGE_REQUEST_INITIALIZED = 'NTR_NME_CNG_REQ_INT',
  NOTARY_NAME_CHANGE_REQUEST_MODIFIED ='NTR_NME_CNG_USR_MOD',
  NOTARY_NAME_CHANGE_DATA_VERIFICATION_CLERK_REJECTED = 'NTR_NME_CNG_DVC_REJ", "Notary Name Change Request Data Verification Clerk Rejected',
}
