export enum NewNotaryRegistrationWorkflowStage {
  NOTARY_REGISTRATION_INITIALIZED = "NTR_REG_USR_INT",
  NOTARY_REGISTRATION_USER_MODIFIED = "NTR_REG_USR_MOD",
  NOTARY_REGISTRATION_DVC_REJECTED = "NTR_REG_DVC_REJ",
}
