export enum Parameters {
  //Notary Registration Workflow
  NOTARY_REG_FEE = 'NOTARY_REG_FEE',
  NOTARY_REG_POST_NORMAL_AMOUNT = 'NOTARY_REG_POST_NORMAL_AMOUNT',
  NOTARY_REG_POST_REGISTERED_AMOUNT = 'NOTARY_REG_POST_REGISTERED_AMOUNT',

  //Search Workflow
  SEARCH_REQUEST_FEE = 'SEARCH_REQUEST_FEE',

  //Extract Workflow
  EXTRACT_REQUEST_FEE = 'EXTRACT_REQUEST_FEE',
  EXTRACT_REQ_POST_NORMAL_AMOUNT = 'EXTRACT_REQ_POST_NORMAL_AMOUNT',
  EXTRACT_REQ_POST_REGISTERED_AMOUNT = 'EXTRACT_REQ_POST_REGISTERED_AMOUNT',

  NOTARY_REG_LANGUAGE_CHANGE = 'NOTARY_LANG_CHG',
  NOTARY_NAME_CHG = 'NOTARY_NAME_CHG',

  LANDREG_CHG_REQ_FEE = 'LANDREG_CHG_REQ_FEE',

  // Pubic user registration
  CITIZEN_REGISTRATION_FEE = 'CITIZEN_REG',
  BANK_REGISTRATION_FEE = 'BANK_REG',
  LAWYER_LAW_FIRM_REGISTRATION_FEE = 'LAWYER_REG',
  STATE_INSTITUTE_REGISTRATION_FEE = 'STA_INS_REG',
  OTHER_INSTITUTE_REGISTRATION_FEE = 'OTH_INS_REG',

  // Notary judicial change
  JUDICIAL_CHANGE_FEE = 'JUD_CHAG',

  NOTARY_NAME_CHANGE_FEE = 'NOTARY_NCH'

}
