export enum Parameters {
  NOTARY_REG_FEE = 'NOTARY_REG_FEE',
  SEARCH_REQUEST_FEE = 'SEARCH_REQUEST_FEE',
  NOTARY_REG_POST_NORMAL_AMOUNT = 'NOTARY_REG_POST_NORMAL_AMOUNT',
  NOTARY_REG_POST_REGISTERED_AMOUNT = 'NOTARY_REG_POST_REGISTERED_AMOUNT',
  NOTARY_REG_LANGUAGE_CHANGE = 'NOTARY_LANG_CHG',
  NOTARY_NAME_CHG = 'NOTARY_NAME_CHG',
}
