export enum Parameters {
  //Notary Registration Workflow
  NOTARY_REG_FEE = 'NOTARY_REG_FEE',
  NOTARY_REG_POST_NORMAL_AMOUNT = 'NOTARY_REG_POST_NORMAL_AMOUNT',
  NOTARY_REG_POST_REGISTERED_AMOUNT = 'NOTARY_REG_POST_REGISTERED_AMOUNT',

  //Search Workflow
  SEARCH_REQUEST_FEE = 'SEARCH_REQUEST_FEE',

  //Extract Workflow
  EXTRACT_REQUEST_FEE = 'EXTRACT_REQUEST_FEE',
  EXTRACT_REQ_POST_NORMAL_AMOUNT = 'EXTRACT_REQ_POST_NORMAL_AMOUNT',
  EXTRACT_REQ_POST_REGISTERED_AMOUNT = 'EXTRACT_REQ_POST_REGISTERED_AMOUNT',

  NOTARY_REG_LANGUAGE_CHANGE = 'NOTARY_LANG_CHG',
  NOTARY_NAME_CHG = 'NOTARY_NAME_CHG',
}
