export enum SearchRequestWorkflowStages {
  SEARCH_REQ_INITIALIZED_FOR_CLARK = "SRC_REQ_INT_FOR_CLARK",
  SEARCH_REQ_INITIALIZED_FOR_ARL= "SRC_REQ_INT_FOR_ARL",
  SEARCH_REQ_REJECTED_BY_ARL = "SRC_REQ_ARL_REJ",
  SEARCH_REQ_APPROVAL_BY_ARL = "SRC_REQ_ARL_APR",
  SEARCH_REQ_MODIFIED = "SRC_REQ_MOD",
}
