export enum WorkflowStageCitizenReg {
  CITIZEN_INIT = 'PU_CT_REG_INT',
  BANK_INIT = 'PU_BNK_REG_INT',
  LAWYER_OR_LAW_FIRM_INIT = 'PU_LWY_REG_INT',
  STATE_INSTITUTE_INIT = 'PU_STI_REG_INT',
  OTHER_INSTITUTE_INIT = 'PU_OI_REG_INT',
}
