export enum WorkflowStages {
  EXTRACT_REQ_INITIALIZED = "EXT_REQ_INT",
  REGISTRATION_REQ_INITIALIZED = "NTR_REG_USR_INT",
  REGISTRATION_REQ_MODIFIED ="NTR_REG_USR_MOD",
  DATA_VERIFICATION_REJECTED="NTR_REG_DVC_REJ",

}
