export enum WorkflowStageCitizenReg {
  PUBLIC_USER_REGISTRATION_INITIALIZED_AS_CITIZEN = 'PU_CT_REG_INT',
  PUBLIC_USER_REGISTRATION_INITIALIZED_AS_BANK = 'PU_BNK_REG_INT',
  PUBLIC_USER_REGISTRATION_INITIALIZED_AS_LAWYER_OR_LAW_FIRM = 'PU_LWY_REG_INT',
  PUBLIC_USER_REGISTRATION_INITIALIZED_AS_STATE_INSTITUTE = 'PU_STI_REG_INT',
  PUBLIC_USER_REGISTRATION_INITIALIZED_AS_OTHER_INSTITUTE = 'PU_OI_REG_INT',
}
