export enum Workflow {
  NOTARY_REGISTRATION = 'NTR_REG_USR_INT',
  CITIZEN_REGISTRATION = 'CITIZEN_REG',
  JUDICIAL_ZONE_CHANGE = 'JUDICIAL_CNG',
  SEARCH_REQUEST = 'SEARCH_REQ',
  EXTRACT_REQUEST = 'EXTRACT_REQ',
  LANGUAGE_CHANGE = 'NOTARY_LANCHN',
  FOLIO_REQUEST_CORRECTION = 'FOLIO_CORRECTION_REQ',
  NOTARY_NAME_CHANGE = 'NTR_NAME_CHG'
}
