export enum Workflow {
  NOTARY_REGISTRATION = 'NTR_REG_USR_INT',
  CITIZEN_REGISTRATION = 'CITIZEN_REG',
  JUDICIAL_ZONE_CHANGE = 'JUDICIAL_CNG',
  SEARCH_REQUEST = 'SEARCH_REQ',
  JUDICIAL_CHANGE_REQUEST_INITIATED = 'NTR_JZC_CNG_USR_INT',
}
